Added functions to turn on and turn off the display
jamwaffles/ssd1331 pull request #11
Opened 2021-03-05 02:28 UTC by David-OConnor

This is useful for battery-powered applications etc, where you regularly turn off and on the display. (The datasheet also calls this "sleep mode", which is appropriate here.

2021-03-05 09:53 UTC, jamwaffles requested changes
Thanks for the PR! I've left some small comment nits, and if you can run `cargo fmt` that should fix CI.

2021-03-05 09:53 UTC, jamwaffles commented on src/display.rs
> +    /// Turn the display off (eg exiting sleep mode)
```suggestion
    /// Turn the display on (exit sleep mode)
```

2021-03-05 09:53 UTC, jamwaffles commented on src/display.rs
> +    /// Turn the display off (sleep mode)
```suggestion
    /// Turn the display off (enter sleep mode)
```

2021-04-04 18:00 UTC, David-OConnor commented
I'm not too good at git. Could you just c+p the functions into master, or merge this as-is then make the tweaks?

2021-04-06 12:09 UTC, jamwaffles approved these changes

2021-04-06 12:09 UTC, merged

2021-04-06 12:09 UTC, jamwaffles commented
Thanks! I've squashed your commits into master so it's still clean. I'll add a changelog entry and get this released.

2021-04-06 12:12 UTC, jamwaffles commented
Released in [0.2.3](https://crates.io/crates/ssd1331/0.2.3).

2021-04-06 16:53 UTC, David-OConnor commented
Sweet!